version: "2"
linters:
  enable:
    - misspell
    - revive
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
    misspell:
      locale: US
    revive:
      rules:
        - name: var-declaration
          severity: warning
          disabled: false
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - job-website-backend
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
